export const english = [
  {
    prompt: "I ……… football every Saturday afternoon",
    A: "am play",
    B: "am playing",
    C: "playing",
    D: "play",
    Ans: "D",
  },
  {
    prompt: "Don’t make too much noise. John ……… to take a nap",
    A: "try",
    B: "is trying",
    C: "tries",
    D: "tried",
    Ans: "B",
  },
  {
    prompt: "Paul ……… his teeth as soon as he wakes up.",
    A: "will brush",
    B: "brushes",
    C: "is brushing",
    D: "brush",
    Ans: "B",
  },
  {
    prompt:
      "He can’t answer the phone. He …….. a shower.This question is required.",
    A: "took",
    B: "is taking",
    C: "take",
    D: "taking",
    Ans: "B",
  },
  {
    prompt: "It ……… many times every winter in New York.",
    A: "snows",
    B: "snowed",
    C: "is snowing",
    D: "is snow",
    Ans: "A",
  },
  {
    prompt: "How many friends ……… to your birthday party?",
    A: "come",
    B: "comes",
    C: "came",
    D: "are coming",
    Ans: "D",
  },
  {
    prompt: "We woke up at 6am and ……….",
    A: "it was snowing",
    B: "it snowed",
    C: "is snows",
    D: "there was snow",
    Ans: "A",
  },
  {
    prompt: "Dogs ……… when they are nervous.",
    A: "bark",
    B: "are barking",
    C: "barking",
    D: "barks",
    Ans: "A",
  },
  {
    prompt: "You can’t borrow my car tomorrow. I ……….. it myself.",
    A: "used",
    B: "use",
    C: "will be using",
    D: "am using",
    Ans: "C",
  },
  {
    prompt: "Ivan ……… his suit today. He usually wears jeans",
    A: "wear",
    B: "is wearing",
    C: "wears",
    D: "wearing",
    Ans: "B",
  },
];

export const hindi = [
  {
    prompt: "निम्नलिखित में से कौन सा शब्द संज्ञा है?",
    A: "खेलना",
    B: "दौड़ना",
    C: "गेंद",
    D: "खाना",
    Ans: "C",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द विशेषण है?",
    A: "खेलना",
    B: "बाल",
    C: "सुंदर",
    D: "बिल्ली",
    Ans: "C",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द सर्वनाम है?",
    A: "खेलना",
    B: "बाल",
    C: "सुंदर",
    D: "वह",
    Ans: "D",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द संज्ञा है?",
    A: "खुश",
    B: "दौड़ना",
    C: "पेड़",
    D: "खाना",
    Ans: "C",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द क्रिया है?",
    A: "मकान",
    B: "खिड़की",
    C: "बिल्ली",
    D: "सोना",
    Ans: "D",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द विशेषण है?",
    A: "खेलना",
    B: "बाल",
    C: "खूबसूरत",
    D: "बिल्ली",
    Ans: "C",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द सर्वनाम है?",
    A: "खेलना",
    B: "बाल",
    C: "सुंदर",
    D: "तुम",
    Ans: "D",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द संज्ञा है?",
    A: "खेलना",
    B: "दौड़ना",
    C: "कुत्ता",
    D: "खाना",
    Ans: "C",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द क्रिया है?",
    A: "बाल",
    B: "खिड़की",
    C: "बिल्ली",
    D: "खेलना",
    Ans: "D",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द क्रिया है?",
    A: "लड़का",
    B: "घर",
    C: "खाना",
    D: "पढ़ना",
    Ans: "D",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द विशेषण है?",
    A: "सुंदर",
    B: "बुरा",
    C: "बड़ा",
    D: "छोटा",
    Ans: "A",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द अव्यय है?",
    A: "कल",
    B: "यहाँ",
    C: "इसलिए",
    D: "फिर",
    Ans: "A",
  },
  {
    prompt: "निम्नलिखित में से कौन सा शब्द क्रियाविशेषण है?",
    A: "बहुत",
    B: "धीरे",
    C: "जल्दी",
    D: "बार-बार",
    Ans: "C",
  },
];

export const french = [
  {
    prompt: "What is the French word for 'house'?",
    A: "Maison",
    B: "Chien",
    C: "Pomme",
    D: "Lire",
    Ans: "A",
  },
  {
    prompt: "What is the French word for 'dog'?",
    A: "Chat",
    B: "Chien",
    C: "Lire",
    D: "Maison",
    Ans: "B",
  },
  {
    prompt: "What is the French word for 'apple'?",
    A: "Chien",
    B: "Lire",
    C: "Pomme",
    D: "Chat",
    Ans: "C",
  },
  {
    prompt: "What is the French word for 'read'?",
    A: "Lire",
    B: "Chat",
    C: "Maison",
    D: "Chien",
    Ans: "A",
  },
  {
    prompt: "What is the French word for 'cat'?",
    A: "Pomme",
    B: "Chat",
    C: "Chien",
    D: "Maison",
    Ans: "B",
  },
  {
    prompt: "What is the French word for 'book'?",
    A: "Livre",
    B: "Chien",
    C: "Pomme",
    D: "Lire",
    Ans: "A",
  },
  {
    prompt: "What is the French word for 'car'?",
    A: "Chat",
    B: "Voiture",
    C: "Lire",
    D: "Maison",
    Ans: "B",
  },
  {
    prompt: "What is the French word for 'tree'?",
    A: "Chien",
    B: "Lire",
    C: "Arbre",
    D: "Chat",
    Ans: "C",
  },
  {
    prompt: "What is the French word for 'eat'?",
    A: "Manger",
    B: "Chat",
    C: "Maison",
    D: "Chien",
    Ans: "A",
  },
  {
    prompt: "What is the French word for 'drink'?",
    A: "Pomme",
    B: "Boire",
    C: "Chien",
    D: "Maison",
    Ans: "B",
  },
];

export const german = [
  {
    prompt: "What is the German word for 'house'?",
    A: "Haus",
    B: "Hund",
    C: "Apfel",
    D: "Lesen",
    Ans: "A",
  },
  {
    prompt: "What is the German word for 'dog'?",
    A: "Katze",
    B: "Hund",
    C: "Lesen",
    D: "Haus",
    Ans: "B",
  },
  {
    prompt: "What is the German word for 'apple'?",
    A: "Hund",
    B: "Lesen",
    C: "Apfel",
    D: "Katze",
    Ans: "C",
  },
  {
    prompt: "What is the German word for 'read'?",
    A: "Lesen",
    B: "Katze",
    C: "Haus",
    D: "Hund",
    Ans: "A",
  },
  {
    prompt: "What is the German word for 'cat'?",
    A: "Apfel",
    B: "Katze",
    C: "Hund",
    D: "Haus",
    Ans: "B",
  },
  {
    prompt: "What is the German word for 'book'?",
    A: "Buch",
    B: "Hund",
    C: "Apfel",
    D: "Lesen",
    Ans: "A",
  },
  {
    prompt: "What is the German word for 'car'?",
    A: "Katze",
    B: "Auto",
    C: "Lesen",
    D: "Haus",
    Ans: "B",
  },
  {
    prompt: "What is the German word for 'tree'?",
    A: "Hund",
    B: "Lesen",
    C: "Baum",
    D: "Katze",
    Ans: "C",
  },
  {
    prompt: "What is the German word for 'eat'?",
    A: "Essen",
    B: "Katze",
    C: "Haus",
    D: "Hund",
    Ans: "A",
  },
  {
    prompt: "What is the German word for 'drink'?",
    A: "Apfel",
    B: "Trinken",
    C: "Hund",
    D: "Haus",
    Ans: "B",
  },
];

export const gujrati = [
  {
    prompt: "What is the Gujarati word for 'house'?",
    A: "ઘર (ghar)",
    B: "કુતરો (kutaro)",
    C: "સફરજન (safarjan)",
    D: "વાંચવું (vanchvu)",
    Ans: "A",
  },
  {
    prompt: "What is the Gujarati word for 'dog'?",
    A: "બિલાડી (bilaadi)",
    B: "કુતરો (kutaro)",
    C: "વાંચવું (vanchvu)",
    D: "ઘર (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Gujarati word for 'apple'?",
    A: "કુતરો (kutaro)",
    B: "વાંચવું (vanchvu)",
    C: "સફરજન (safarjan)",
    D: "બિલાડી (bilaadi)",
    Ans: "C",
  },
  {
    prompt: "What is the Gujarati word for 'read'?",
    A: "વાંચવું (vanchvu)",
    B: "બિલાડી (bilaadi)",
    C: "ઘર (ghar)",
    D: "કુતરો (kutaro)",
    Ans: "A",
  },
  {
    prompt: "What is the Gujarati word for 'cat'?",
    A: "સફરજન (safarjan)",
    B: "બિલાડી (bilaadi)",
    C: "કુતરો (kutaro)",
    D: "ઘર (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Gujarati word for 'book'?",
    A: "પુસ્તક (pustak)",
    B: "કુતરો (kutaro)",
    C: "સફરજન (safarjan)",
    D: "વાંચવું (vanchvu)",
    Ans: "A",
  },
  {
    prompt: "What is the Gujarati word for 'car'?",
    A: "બિલાડી (bilaadi)",
    B: "કાર (kaar)",
    C: "વાંચવું (vanchvu)",
    D: "ઘર (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Gujarati word for 'tree'?",
    A: "કુતરો (kutaro)",
    B: "વાંચવું (vanchvu)",
    C: "વૃક્ષ (vrux)",
    D: "બિલાડી (bilaadi)",
    Ans: "C",
  },
  {
    prompt: "What is the Gujarati word for 'eat'?",
    A: "ખોરવું (khorvu)",
    B: "બિલાડી (bilaadi)",
    C: "ઘર (ghar)",
    D: "કુતરો (kutaro)",
    Ans: "A",
  },
  {
    prompt: "What is the Gujarati word for 'drink'?",
    A: "સફરજન (safarjan)",
    B: "પીવું (peevu)",
    C: "કુતરો (kutaro)",
    D: "ઘર (ghar)",
    Ans: "B",
  },
];

export const marathi = [
  {
    prompt: "What is the Marathi word for 'house'?",
    A: "घर (ghar)",
    B: "कुत्रा (kutra)",
    C: "सफरचंद (sapharachand)",
    D: "वाचणे (vachane)",
    Ans: "A",
  },
  {
    prompt: "What is the Marathi word for 'dog'?",
    A: "मांजर (manjar)",
    B: "कुत्रा (kutra)",
    C: "वाचणे (vachane)",
    D: "घर (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Marathi word for 'apple'?",
    A: "कुत्रा (kutra)",
    B: "वाचणे (vachane)",
    C: "सफरचंद (sapharachand)",
    D: "मांजर (manjar)",
    Ans: "C",
  },
  {
    prompt: "What is the Marathi word for 'read'?",
    A: "वाचणे (vachane)",
    B: "मांजर (manjar)",
    C: "घर (ghar)",
    D: "कुत्रा (kutra)",
    Ans: "A",
  },
  {
    prompt: "What is the Marathi word for 'cat'?",
    A: "सफरचंद (sapharachand)",
    B: "मांजर (manjar)",
    C: "कुत्रा (kutra)",
    D: "घर (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Marathi word for 'book'?",
    A: "पुस्तक (pustak)",
    B: "कुत्रा (kutra)",
    C: "सफरचंद (sapharachand)",
    D: "वाचणे (vachane)",
    Ans: "A",
  },
  {
    prompt: "What is the Marathi word for 'car'?",
    A: "मांजर (manjar)",
    B: "कार (kaar)",
    C: "वाचणे (vachane)",
    D: "घर (ghar)",
    Ans: "B",
  },
  {
    prompt: "What is the Marathi word for 'tree'?",
    A: "कुत्रा (kutra)",
    B: "वाचणे (vachane)",
    C: "झाड (zhaad)",
    D: "मांजर (manjar)",
    Ans: "C",
  },
  {
    prompt: "What is the Marathi word for 'eat'?",
    A: "खाणे (khane)",
    B: "मांजर (manjar)",
    C: "घर (ghar)",
    D: "कुत्रा (kutra)",
    Ans: "A",
  },
  {
    prompt: "What is the Marathi word for 'drink'?",
    A: "सफरचंद (sapharachand)",
    B: "पिणे (pine)",
    C: "कुत्रा (kutra)",
    D: "घर (ghar)",
    Ans: "B",
  },
];

export const telugu = [
  {
    prompt: "What is the Telugu word for 'house'?",
    A: "ఇల్లు (illu)",
    B: "కుక్క (kukka)",
    C: "ఆపిల్ (aapil)",
    D: "చదువు (chaduvu)",
    Ans: "A"
},
{
    prompt: "What is the Telugu word for 'dog'?",
    A: "పిల్లి (pilli)",
    B: "కుక్క (kukka)",
    C: "చదువు (chaduvu)",
    D: "ఇల్లు (illu)",
    Ans: "B"
},
{
    prompt: "What is the Telugu word for 'apple'?",
    A: "కుక్క (kukka)",
    B: "చదువు (chaduvu)",
    C: "ఆపిల్ (aapil)",
    D: "పిల్లి (pilli)",
    Ans: "C"
},
{
    prompt: "What is the Telugu word for 'read'?",
    A: "చదువు (chaduvu)",
    B: "పిల్లి (pilli)",
    C: "ఇల్లు (illu)",
    D: "కుక్క (kukka)",
    Ans: "A"
},
{
    prompt: "What is the Telugu word for 'cat'?",
    A: "ఆపిల్ (aapil)",
    B: "పిల్లి (pilli)",
    C: "కుక్క (kukka)",
    D: "ఇల్లు (illu)",
    Ans: "B"
},
{
    prompt: "What is the Telugu word for 'book'?",
    A: "పుస్తకం (pustakam)",
    B: "కుక్క (kukka)",
    C: "ఆపిల్ (aapil)",
    D: "చదువు (chaduvu)",
    Ans: "A"
},
{
    prompt: "What is the Telugu word for 'car'?",
    A: "పిల్లి (pilli)",
    B: "కారు (kaaru)",
    C: "చదువు (chaduvu)",
    D: "ఇల్లు (illu)",
    Ans: "B"
},
{
    prompt: "What is the Telugu word for 'tree'?",
    A: "కుక్క (kukka)",
    B: "చదువు (chaduvu)",
    C: "చెట్టు (chettu)",
    D: "పిల్లి (pilli)",
    Ans: "C"
},
{
    prompt: "What is the Telugu word for 'eat'?",
    A: "తిను (tinu)",
    B: "పిల్లి (pilli)",
    C: "ఇల్లు (illu)",
    D: "కుక్క (kukka)",
    Ans: "A"
},
{
    prompt: "What is the Telugu word for 'drink'?",
    A: "ఆపిల్ (aapil)",
    B: "తాగు (taagu)",
    C: "కుక్క (kukka)",
    D: "ఇల్లు (illu)",
    Ans: "B"
}
]
